sudo: required
services:
  - docker
  
before_install:
  - docker build -t calebbray/docker-react -f Dockerfile.dev .

script:
  - docker run calebbray/docker-react CI=true npm run test -- --coverage
